/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harrypotter;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author KELVIN
 */
public class bagPanel extends javax.swing.JPanel {

    /**
     * Creates new form bagPanel
     */
    public bagPanel() {
        initComponents();
        this.setSize(800,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BAG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        add(jPanel1);
        jPanel1.setBounds(50, 54, 466, 70);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(1);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(50, 180, 200, 310);

        jPanel2.setBackground(new java.awt.Color(153, 153, 0));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ITEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2);
        jPanel2.setBounds(90, 140, 110, 30);

        jButton1.setFont(new java.awt.Font("Tekton Pro Ext", 3, 36)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(20, 530, 190, 60);

        jPanel3.setBackground(new java.awt.Color(153, 153, 0));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WAND");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        add(jPanel3);
        jPanel3.setBounds(500, 230, 210, 33);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(jTextField1);
        jTextField1.setBounds(310, 190, 70, 60);

        jButton3.setText("DELETE ITEM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(290, 260, 120, 23);

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(1);
        jTextArea5.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jTextArea5.setRows(1);
        jScrollPane5.setViewportView(jTextArea5);

        add(jScrollPane5);
        jScrollPane5.setBounds(500, 280, 210, 50);

        jTextArea6.setEditable(false);
        jTextArea6.setColumns(1);
        jTextArea6.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jTextArea6.setRows(1);
        jScrollPane6.setViewportView(jTextArea6);

        add(jScrollPane6);
        jScrollPane6.setBounds(280, 500, 210, 30);

        jTextArea7.setEditable(false);
        jTextArea7.setColumns(1);
        jTextArea7.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jTextArea7.setRows(1);
        jScrollPane7.setViewportView(jTextArea7);

        add(jScrollPane7);
        jScrollPane7.setBounds(280, 420, 210, 30);

        jTextArea8.setEditable(false);
        jTextArea8.setColumns(1);
        jTextArea8.setFont(new java.awt.Font("Monotype Corsiva", 3, 18)); // NOI18N
        jTextArea8.setRows(1);
        jScrollPane8.setViewportView(jTextArea8);

        add(jScrollPane8);
        jScrollPane8.setBounds(280, 460, 210, 30);

        jButton2.setText("CHANGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(500, 500, 110, 30);

        jButton4.setText("CHANGE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(500, 420, 110, 30);

        jButton5.setText("CHANGE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(500, 460, 110, 30);
        add(jTextField2);
        jTextField2.setBounds(620, 500, 50, 30);
        add(jTextField3);
        jTextField3.setBounds(620, 420, 50, 30);
        add(jTextField4);
        jTextField4.setBounds(620, 460, 50, 30);

        jPanel4.setBackground(new java.awt.Color(153, 153, 0));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("USED ITEMS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        add(jPanel4);
        jPanel4.setBounds(280, 380, 210, 33);

        jButton6.setText("REMOVE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(680, 500, 110, 30);

        jButton7.setText("REMOVE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(680, 420, 110, 30);

        jButton8.setText("REMOVE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8);
        jButton8.setBounds(680, 460, 110, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        temp.goToMainMenu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        String input = jTextField1.getText();
        int index = Integer.parseInt(input);
        
        if(index < 0 || index >= temp.p1.listItem.size()){
            JOptionPane.showMessageDialog(null, "Invalid input!");
        }else{
            JOptionPane.showMessageDialog(null, "Item deleted!");
            temp.p1.listItem.remove(index);
            jTextArea1.setText("");
            for (int i = 0; i < temp.p1.listItem.size(); i++) {
                jTextArea1.append("["+i+"] "+temp.p1.listItem.get(i).nama+"\n");
            }
        }
        
        jTextField1.setText("");
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
       //System.out.println("BEFORE: "+temp.p1.hp);
       String input = jTextField3.getText();
       int index = Integer.parseInt(input);
       
       if(index < 0 || index >= temp.p1.listItem.size()){
           JOptionPane.showMessageDialog(null, "Invalid input!");
       }else{
           if(temp.p1.usedItem[0].idEffect != -1){
               temp.p1.listItem.add(temp.p1.usedItem[0]);
           }
           temp.p1.usedItem[0] = new usable(temp.p1.listItem.get(index).idEffect);
           temp.p1.listItem.remove(index);
       }
       jTextArea7.setText(temp.p1.usedItem[0].nama);
       jTextField3.setText("");
       jTextArea1.setText("");
       for (int i = 0; i < temp.p1.listItem.size(); i++) {
                jTextArea1.append("["+i+"] "+temp.p1.listItem.get(i).nama+"\n");
            }
       
       //System.out.println("AFTER: "+temp.p1.hp);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
       
       String input = jTextField4.getText();
       int index = Integer.parseInt(input);
       
       if(index < 0 || index >= temp.p1.listItem.size()){
           JOptionPane.showMessageDialog(null, "Invalid input!");
       }else{
           if(temp.p1.usedItem[1].idEffect != -1){
               temp.p1.listItem.add(temp.p1.usedItem[0]);
           }
           temp.p1.usedItem[1] = new usable(temp.p1.listItem.get(index).idEffect);
           temp.p1.listItem.remove(index);
       }
       jTextArea8.setText(temp.p1.usedItem[1].nama);
       jTextField4.setText("");
       jTextArea1.setText("");
       for (int i = 0; i < temp.p1.listItem.size(); i++) {
                jTextArea1.append("["+i+"] "+temp.p1.listItem.get(i).nama+"\n");
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
       
       String input = jTextField2.getText();
       int index = Integer.parseInt(input);
       
       if(index < 0 || index >= temp.p1.listItem.size()){
           JOptionPane.showMessageDialog(null, "Invalid input!");
       }else{
           if(temp.p1.usedItem[2].idEffect != -1){
               temp.p1.listItem.add(temp.p1.usedItem[0]);
           }
           temp.p1.usedItem[2] = new usable(temp.p1.listItem.get(index).idEffect);
           temp.p1.listItem.remove(index);
       }
       jTextArea6.setText(temp.p1.usedItem[2].nama);
       jTextField2.setText("");
       jTextArea1.setText("");
       for (int i = 0; i < temp.p1.listItem.size(); i++) {
                jTextArea1.append("["+i+"] "+temp.p1.listItem.get(i).nama+"\n");
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        if(temp.p1.usedItem[0].idEffect != -1){
               temp.p1.listItem.add(temp.p1.usedItem[0]);
        }
        temp.p1.usedItem[0] = new usable(-1);
        jTextArea7.setText(temp.p1.usedItem[0].nama);
        jTextArea1.setText("");
        for (int i = 0; i < temp.p1.listItem.size(); i++) {
                jTextArea1.append("["+i+"] "+temp.p1.listItem.get(i).nama+"\n");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        if(temp.p1.usedItem[1].idEffect != -1){
               temp.p1.listItem.add(temp.p1.usedItem[1]);
        }
        temp.p1.usedItem[1] = new usable(-1);
        jTextArea8.setText(temp.p1.usedItem[1].nama);
        jTextArea1.setText("");
        for (int i = 0; i < temp.p1.listItem.size(); i++) {
                jTextArea1.append("["+i+"] "+temp.p1.listItem.get(i).nama+"\n");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        if(temp.p1.usedItem[2].idEffect != -1){
               temp.p1.listItem.add(temp.p1.usedItem[2]);
        }
        temp.p1.usedItem[2] = new usable(-1);
        jTextArea6.setText(temp.p1.usedItem[2].nama);
        jTextArea1.setText("");
        for (int i = 0; i < temp.p1.listItem.size(); i++) {
                jTextArea1.append("["+i+"] "+temp.p1.listItem.get(i).nama+"\n");
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    public void rebuild(){
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        for (int i = 0; i < temp.p1.listItem.size(); i++) {
            jTextArea1.append("["+i+"] "+temp.p1.listItem.get(i).nama+"\n");
        }
        
        jTextArea7.setText(temp.p1.usedItem[0].nama);
        jTextArea8.setText(temp.p1.usedItem[1].nama);
        jTextArea6.setText(temp.p1.usedItem[2].nama);
        
        jTextArea5.setText(temp.p1.usedWand.nama);
        
        //BACKGROUND LAST
        ImageIcon raw1 = new ImageIcon("Image/bagBackground.jpg");
        Image img1 = raw1.getImage();
        Image newImg1 = img1.getScaledInstance(800, 600, Image.SCALE_SMOOTH);
        ImageIcon finalImage1 = new ImageIcon(newImg1);
        JLabel lblBackground = new JLabel(finalImage1);
        
        lblBackground.setBounds(0, 0, 800, 600);
        this.add(lblBackground);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
