/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harrypotter;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author KELVIN
 */
public class dormb1 extends javax.swing.JPanel {
    int x = 0;
    int posA = 0;
    int posB = 0;
    int start = 0;
    Timer myTimer;
    String word = "You're a hardworker, seeking for justice, loyal, and\n" +
"patience...";
    int wordSize = word.length();
    
    
    
    public dormb1() {
        initComponents();
        this.setSize(800,600);
        
        ImageIcon raw = new ImageIcon("Image/ng8_Background.jpg");
        Image img = raw.getImage();
        Image newImg = img.getScaledInstance(900, 700, Image.SCALE_SMOOTH);
        ImageIcon finalImage = new ImageIcon(newImg);
        JLabel lblBackground = new JLabel(finalImage);
        
        //McGonagall Potrait
        ImageIcon raw1 = new ImageIcon("Image/mcGonBox.jpg");
        Image img1 = raw1.getImage();
        Image newImg1 = img1.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon finalImage1 = new ImageIcon(newImg1);
        JLabel mGB = new JLabel(finalImage1);
        
        this.add(mGB);
        this.add(lblBackground);
        lblBackground.setBounds(0, 0, 900, 700);
        
        myTimer = new Timer(50,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                if(x < word.length()){
                jTextArea1.append(String.valueOf(word.charAt(x)));
                x++;
                posA--;
                posB--;
                lblBackground.setLocation(posA, posB);
                }else{

                }
            }
        });
        
        myTimer.start();
    }
    
    public void rebuild(){
        x = 0;
        posA = 0;
        posB = 0;
        jTextArea1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 153, 0));
        jTextArea1.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jTextArea1.setTabSize(0);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 392, 784, 200);

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 200)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("?");
        add(jLabel1);
        jLabel1.setBounds(300, 80, 154, 245);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        keyPressed();
    }//GEN-LAST:event_formMouseClicked
    public void keyPressed(){
        if(x == wordSize){
            mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
            temp.goToDb2();
        }else{
            jTextArea1.setText(word);
            x = wordSize;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
