/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harrypotter;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author KELVIN
 */
public class dorma2 extends javax.swing.JPanel {
    int x = 0;
    int posA = 0;
    int posB = 0;
    int start = 0;
    Timer myTimer;
    String word = "You're brave, you have a great courage, nerve, and\n" +
"chivalry...";
    int wordSize = word.length();
    
    
    
    public dorma2() {
        initComponents();
        this.setSize(800,600);
        
        ImageIcon raw = new ImageIcon("Image/ng8_Background.jpg");
        Image img = raw.getImage();
        Image newImg = img.getScaledInstance(800, 600, Image.SCALE_SMOOTH);
        ImageIcon finalImage = new ImageIcon(newImg);
        JLabel lblBackground = new JLabel(finalImage);
        
        //McGonagall Potrait
        ImageIcon raw1 = new ImageIcon("Image/mcGonBox.jpg");
        Image img1 = raw1.getImage();
        Image newImg1 = img1.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon finalImage1 = new ImageIcon(newImg1);
        JLabel mGB = new JLabel(finalImage1);
        
        this.add(mGB);
        this.add(lblBackground);
        lblBackground.setBounds(0, 0, 800, 600);
        
        
        
    }
    
    public void rebuild(){
        x = 0;
        posA = 0;
        posB = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Vivaldi", 0, 200)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\KULIAH\\SEM 2\\PBO\\Projek Harry Potter\\HarryPotter\\Image\\gryffindorLogo.png")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(10, 100, 790, 245);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setFont(new java.awt.Font("Pristina", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("GRYFFINDOR");
        jPanel1.add(jLabel2);

        add(jPanel1);
        jPanel1.setBounds(0, 340, 800, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        keyPressed();
    }//GEN-LAST:event_formMouseClicked
    public void keyPressed(){
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        temp.p1.str = 32;
            temp.p1.intel = 18;
            temp.p1.agi = 28;
            temp.p1.strGrowth = 8;
            temp.p1.intGrowth = 4;
            temp.p1.agiGrowth = 4;
            temp.p1.hp = temp.p1.str * 30;
            temp.p1.mana = temp.p1.intel * 20;
            temp.p1.basicAtk = temp.p1.agi * 2;
            temp.p1.magicDmg = temp.p1.intel * 3;
        temp.goToTutorPanel();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
