
package harrypotter;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author KELVIN
 */
public class exercise extends javax.swing.JPanel {
    
    player tempP1;
    int npcHpMax;
    int playerMaxHP;
    bot dummy;
    int randomWord;
    int wordAt = 0;
    int stop;
    String wordNow;
    String letterNow;
    int resetPlayer = 2;
    int time = 1000;
    int botTime;
    Timer myTimer;
    public exercise() {
        initComponents();
        this.setSize(800,600);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 51, 0)));
        jPanel1.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(1);
        jTextArea1.setRows(1);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 30, 476, 30);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(1);
        jTextArea2.setRows(1);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(290, 90, 476, 30);

        jLabel4.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NPC");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 70, 360, 19);

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PLAYERNAME");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 10, 360, 19);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("2");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(720, 10, 40, 20);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(20, 20, 240, 96);

        add(jPanel1);
        jPanel1.setBounds(10, 460, 780, 130);

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NPC_HP/NPC_HP_MAX");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 10, 310, 20);

        add(jPanel2);
        jPanel2.setBounds(450, 20, 330, 40);

        jPanel3.setBackground(new java.awt.Color(0, 51, 0));
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PlayerHP/PlayerHPMax");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 10, 310, 20);

        add(jPanel3);
        jPanel3.setBounds(20, 20, 330, 40);

        jLabel8.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("VS");
        add(jLabel8);
        jLabel8.setBounds(360, 30, 80, 40);
        add(jLabel9);
        jLabel9.setBounds(550, 150, 200, 300);
        add(jLabel10);
        jLabel10.setBounds(50, 150, 200, 300);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("PlayerName");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel6);
        jPanel6.setBounds(20, 60, 160, 20);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("NPC_Name");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel7);
        jPanel7.setBounds(610, 60, 170, 20);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(340, 400, 120, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        temp.goToMainMenu();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void keyPressed(){
        String temp = jTextArea1.getText();
        hitBot(temp);
        
        jTextArea1.setText("");
        
    }
    
    public void insertSpell(char e){
        jTextArea1.append(String.valueOf(e));
    }
    public void rebuild(){
        jTextArea1.setText("");
        jTextArea2.setText("");
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        temp.kodePanel = "exe";
        temp.p1.usedWand = new wand(-1);
        
        jTextArea3.setText(temp.p1.usedItem[0].nama+"\n"+temp.p1.usedItem[1].nama+"\n"+temp.p1.usedItem[2].nama);
        //PLAYER
        int level = temp.p1.level;
        tempP1 = (player) temp.p1.clone();
        tempP1.hp = 500;
        playerMaxHP = tempP1.hp;
        jLabel7.setText(tempP1.hp+"/"+temp.p1.hp);
        jLabel11.setText(tempP1.nama);
        ImageIcon player = new ImageIcon("Image/playerArena.png");
        jLabel10.setIcon(player);
        //RANDOM BOT
        int BotID = 0;
        
        
        
        
        //BOT
        dummy = new bot(0);
        ImageIcon lblBot = new ImageIcon("Image/NPC_dummy.png");
        jLabel9.setIcon(lblBot);
        
        npcHpMax = dummy.hp;
        jLabel6.setText(dummy.hp+"/"+npcHpMax);
        jLabel12.setText(dummy.nama);
        ArrayList<String> botSpell = dummy.spell;
        botTime = dummy.spd;
        wordAt = 0;
        int randomWord = (int)(Math.random()*dummy.spell.size());
        System.out.println(randomWord);
        System.out.println(botSpell.size());
        //BACKGROUND ON THE LAST ORDER
        ImageIcon raw1 = new ImageIcon("Image/BackgroundArena.jpeg");
        Image img1 = raw1.getImage();
        Image newImg1 = img1.getScaledInstance(800, 600, Image.SCALE_SMOOTH);
        ImageIcon finalImage1 = new ImageIcon(newImg1);
        JLabel lblBackground = new JLabel(finalImage1);
        
        lblBackground.setBounds(0, 0, 800, 600);
        this.add(lblBackground);
        
        
        //GAME SYSTEM
        
        //PLAYER RESET TIME
        myTimer = new Timer(time,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                
                if(resetPlayer > 0){
                    resetPlayer--;
                }else{
                    resetPlayer = 2;
                    jTextArea1.setText("");
                }
                System.out.println(resetPlayer);
                jLabel15.setText(String.valueOf(resetPlayer));
            }
        });
        myTimer.start();
        
        //BOT THREAD
        
        Timer winTimer = new Timer(1, new ActionListener(){
           @Override
           public void actionPerformed(ActionEvent e){
               if(dummy.hp <= 0 || tempP1.hp <= 0){
                   if(dummy.hp <= 0){
                       JOptionPane.showMessageDialog(null, "YOU WIN!\n you got : \n"+dummy.goldDrop+"G\n"+dummy.xpDrop+"EXP");
                       myTimer.stop();
                       temp.p1.gold += dummy.goldDrop;
                       temp.p1.xp += dummy.xpDrop;
                       temp.goToArcade();
                   }else if(tempP1.hp <= 0){
                       JOptionPane.showMessageDialog(null, "YOU LOSE!\nBack to Main Menu.");
                       myTimer.stop();
                       temp.goToMainMenu();
                   }
                   
                   Timer x = (Timer)e.getSource();
                   x.stop();
               }
           }
        });
        winTimer.start();
    }
    public void randomBot(){
        wordAt = 0;
        int randomWord = (int)(Math.random()*dummy.spell.size());
        wordNow = dummy.spell.get(randomWord);
    }
    
    public void hitBot(String spell){
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        int cekSpell =  1;
        System.out.println(dummy.hp);
        
        if(spell.equals("incendio")){
            JOptionPane.showMessageDialog(null, "A firemaking spell\nDMG 200+MagicDmg");
        }else if(spell.equals("petrificus totalus")){
            JOptionPane.showMessageDialog(null, "The full body bind\nStun 1.8 sec");
        }else if(spell.equals("attack")){
            JOptionPane.showMessageDialog(null, "Simple ATTACK!");
        }else if(spell.equals("lumos")){
            JOptionPane.showMessageDialog(null, "Summon a very bright light\nStun 1.2 sec");
        }else if(spell.equals("wingardium leviosa")){
            JOptionPane.showMessageDialog(null, "Levitate the victim and let it fall\n Stun 0.8 sec and DMG 320");
        }else if(spell.equals("diffindo")){
            JOptionPane.showMessageDialog(null, "Cut litteraly everything\nDMG 310 + Magic DMG");
        }else if(spell.equals("confundo")){
            JOptionPane.showMessageDialog(null, "A charm causes confusion\nStun 3.6 sec");
        }else if(spell.equals("protego")){
            JOptionPane.showMessageDialog(null, "A full defend spell\n Block DMG 3.5 sec");
        }else if(spell.equals("expelliarnus")){
            JOptionPane.showMessageDialog(null, "Spell for removing an object\n Stun 4 sec");
        }else if(spell.equals("stupify")){
            JOptionPane.showMessageDialog(null, "Spell to knock out the enemy\nDMG 390 + Magic DMG");
        }else if(spell.equals("expecto paronum")){
            JOptionPane.showMessageDialog(null, "Summon patronum, block DMG for 4s, and heal 9% HP");
        }else if(spell.equals("riddikulus")){
            JOptionPane.showMessageDialog(null, "Change the enemy to funny object\nStun for 2sec");
        }else if(spell.equals("bombarda")){
            JOptionPane.showMessageDialog(null, "Deal an explosive spell\n DMG 400 + Magic DMG");
        }else if(spell.equals("bombarda maximal")){
            JOptionPane.showMessageDialog(null, "Deal a big explosive spell\nDMG 510 + Magic DMG");
        }else if(spell.equals("sectum sempra")){
            JOptionPane.showMessageDialog(null, "A flying curse to injure\nDMG 5*MagicDMG");
        }else if(spell.equals("confringo")){
            JOptionPane.showMessageDialog(null, "Burst the enemy with fire\nDMG 580+Magic DMG");
        }else if(spell.equals("diminuendo")){
            JOptionPane.showMessageDialog(null, "Force the enemy to shrink\nStun 4.8 sec");
        }else if(spell.equals("episkey")){
            JOptionPane.showMessageDialog(null, "Healing spell\n Heal 320+INT*2 HP");
        }else if(spell.equals("fiendfyre")){
            JOptionPane.showMessageDialog(null, "Create a great spirit of fire\nDMG 12*Magic DMG");
        }else if(spell.equals("firestorm")){
            JOptionPane.showMessageDialog(null, "produce a ring of fire\nDMG 15*Magic DMG");
        }else if(spell.equals("crucio")){
            JOptionPane.showMessageDialog(null, "One of the three unforgivable spell\nthe curese causes agonizing pain\nStun 5sec and DMG 6*magic DMg");
        }else if(spell.equals("avada kedavra")){
            JOptionPane.showMessageDialog(null, "One of the three unforgivable spell\npowerful curse which instanly kill\nthe victim\n50% chance of instant kill");
        }
        
        jLabel6.setText(""+dummy.hp+"/"+npcHpMax);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
