/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harrypotter;

import com.sun.javafx.collections.ArrayListenerHelper;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author KELVIN
 */
public class magicSchool extends javax.swing.JPanel { 
   
    public magicSchool() {
        initComponents();
        this.setSize(800,600);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SCHOOL OF MAGIC");

        jTextField1.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Insert the spell name :");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        temp.goToMainMenu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String input = jTextField1.getText();
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        
        int level = temp.p1.level;
        int busy = temp.p1.busy;
        int hh,mm,ss;
        hh = temp.p1.hh;
        mm = temp.p1.mm;
        ss = temp.p1.ss;
        
        if(busy == 1){
            JOptionPane.showMessageDialog(null, "Player is busy\n"+hh+":"+mm+":"+ss+" remaining");
        }else{
            if(input.equals("petrificus totallus")){
                if(level >= 1){
                    temp.learn(input,0,0,10);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("lumos")){//NAMA SPELL
                //ISA DIDAPET DI LEVEL BERAPA
                if(level >= 4){
                    temp.learn(input,0,0,30);
                    //temp.learn(input,hh,mm,ss); <--WAKTUNE, methodnya learn ws tk bkin tinggal pake ae gampang to :P
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                    //KALO level ga mencukupi
                }
            }else if(input.equals("wingardium leviosa")){
                if(level >= 7){
                    temp.learn(input,0,1,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("diffindo")){
                if(level >= 9){
                    temp.learn(input,0,5,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("confundo")){
                if(level >= 12){
                    temp.learn(input,0,8,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("protego")){
                if(level >= 14){
                    temp.learn(input,0,15,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }
            else if(input.equals("expelliarmus")){
                if(level >= 15){
                    temp.learn(input,0,20,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("stupify")){
                if(level >= 18){
                    temp.learn(input,0,30,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("expecto patronum")){
                if(level >= 21){
                    temp.learn(input,0,45,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("riddikulus")){
                if(level >= 21){
                    temp.learn(input,0,45,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("bombarda")){
                if(level >= 25){
                    temp.learn(input,0,55,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }
            else if(input.equals("bombarda maxima")){
                if(level >= 28){
                    temp.learn(input,2,0,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("sectumsempra")){
                if(level >= 33){
                    temp.learn(input,2,30,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }
            else if(input.equals("confringo")){
                if(level >= 35){
                    temp.learn(input,2,45,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("diminuendo")){
                if(level >= 36){
                    temp.learn(input,3,0,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("episkey")){
                if(level >= 40){
                    temp.learn(input,4,0,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("fiendfyre")){
                if(level >= 46){
                    temp.learn(input,5,0,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("firestorm")){
                if(level >= 46){
                    temp.learn(input,5,0,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else if(input.equals("crucio")){
                if(level >= 48){
                    temp.learn(input,7,0,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }
            else if(input.equals("avada kedavra")){
                if(level >= 50){
                    temp.learn(input,9,0,0);
                }else{
                    JOptionPane.showMessageDialog(null, "Level is not enough!");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Invalid spell!");
            }
            
        }
        
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed
    public void rebuild(){
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        
        int level = temp.p1.level;
        int busy = temp.p1.busy;
        ArrayList<String> ownedSpell = temp.p1.spell;
        
        if(busy == 0){
            jTextArea1.setText("Level 1 - petrificus totallus - stun 1.8 sec [00:00:10]\n" +
"Level 4 - lumos - stun 1.2 sec [00:00:30]\n" +
"Level 7 - wingardium leviosa - stun 0.8 sec + 320 DMG [00:01:00]\n" +
"Level 9 - diffindo - 310 + MagicDmg DMG [00:05:00]\n" +
"Level 12 - confundo - stun 3.6 sec [00:08:00]\n" +
"Level 14 - protego - 1 sec DMG block [00:15:00]\n" +
"Level 15 - expelliarmus - stun 4 sec [00:20:00]\n" +
"Level 18 - stupify - 390 + MagicDmg DMG [00:30:00]\n" +
"Level 21 - expecto patronum - 2 sec DMG block + 9% HP heal [00:45:00]\n" +
"Level 21 - riddikulus - 2.2 sec stun [00:45:00]\n" +
"Level 25 - bombarda - 400 + MagicDmg DMG [00:55:00]\n" +
"Level 28 - bombarda maxima - 510 + MagicDmg DMG [02:00:00]\n" +
"Level 33 - sectumsempra - 5*MagicDmg DMG [02:30:00]\n" +
"Level 35 - confringo - 580+MagicDmg [02:45:00]\n" +
"Level 36 - diminuendo - 4.8 sec stun [03:00:00]\n" +
"Level 40 - episkey - 320 + Intel*2 HP Heal [04:00:00]\n" +
"Level 46 - fiendfyre - 12*MagicDmg DMG [05:00:00]\n" +
"Level 46 - firestorm - 16*MagicDmg DMG [05:00:00]\n" +
"Level 48 - crucio - stun 5 sec + 6*MagicDmg DMG [07:00:00]\n" +
"Level 50 - avada kedavra - 15% Instant Kill [09:00:00]");
        }else{
            jTextArea1.setText("Your character is busy learning something");
        }
        
        
         //BACKGROUND LAST
        ImageIcon raw1 = new ImageIcon("Image/schoolBackground.jpg");
        Image img1 = raw1.getImage();
        Image newImg1 = img1.getScaledInstance(800, 600, Image.SCALE_SMOOTH);
        ImageIcon finalImage1 = new ImageIcon(newImg1);
        JLabel lblBackground = new JLabel(finalImage1);
        
        lblBackground.setBounds(0, 0, 800, 600);
        this.add(lblBackground);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
