/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harrypotter;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author KELVIN
 */
public class ng9Transition extends javax.swing.JPanel {
    
    
    
    
    public ng9Transition() {
        initComponents();
        this.setSize(800,600);
        
        ImageIcon raw = new ImageIcon("Image/ng9_Background.jpg");
        Image img = raw.getImage();
        Image newImg = img.getScaledInstance(800, 600, Image.SCALE_SMOOTH);
        ImageIcon finalImage = new ImageIcon(newImg);
        JLabel lblBackground = new JLabel(finalImage);
        
        this.add(lblBackground);
        lblBackground.setBounds(0, 0, 800, 600);
        
    }
    
    public void rebuild(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tequila Sunset", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        add(jLabel2);
        jLabel2.setBounds(714, 171, 612, 135);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GET READY!");
        add(jLabel1);
        jLabel1.setBounds(100, 40, 578, 545);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        keyPressed();
    }//GEN-LAST:event_formMouseClicked
    public void keyPressed(){
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        
        temp.goToDq0();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
