/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harrypotter;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author KELVIN
 */
public class storyPanel extends javax.swing.JPanel {

    /**
     * Creates new form storyPanel
     */
    public storyPanel() {
        initComponents();
        this.setSize(800,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        lbl9 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(10, 542, 129, 47);
        add(lbl6);
        lbl6.setBounds(130, 210, 100, 100);
        add(lbl7);
        lbl7.setBounds(250, 210, 100, 100);
        add(lbl8);
        lbl8.setBounds(370, 210, 100, 100);
        add(lbl9);
        lbl9.setBounds(490, 210, 100, 100);
        add(lbl10);
        lbl10.setBounds(610, 210, 100, 100);
        add(lbl15);
        lbl15.setBounds(610, 320, 100, 100);
        add(lbl14);
        lbl14.setBounds(490, 320, 100, 100);
        add(lbl13);
        lbl13.setBounds(370, 320, 100, 100);
        add(lbl12);
        lbl12.setBounds(250, 320, 100, 100);
        add(lbl11);
        lbl11.setBounds(130, 320, 100, 100);
        add(lbl1);
        lbl1.setBounds(130, 100, 100, 100);
        add(lbl2);
        lbl2.setBounds(250, 100, 100, 100);
        add(lbl3);
        lbl3.setBounds(370, 100, 100, 100);
        add(lbl4);
        lbl4.setBounds(490, 100, 100, 100);
        add(lbl5);
        lbl5.setBounds(610, 100, 100, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        
        temp.goToMainMenu();
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void rebuild(){
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        
        int level = temp.p1.story;
        if(level >= 1){
            ImageIcon lbl = new ImageIcon("Image/story1.jpg");
            lbl1.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl1.setIcon(lbl);
        }
        
        if(level >= 2){
            ImageIcon lbl = new ImageIcon("Image/story2.jpg");
            lbl2.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl2.setIcon(lbl);
        }
        if(level >= 3){
            ImageIcon lbl = new ImageIcon("Image/story3.jpg");
            lbl3.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl3.setIcon(lbl);
        }
        if(level >= 4){
            ImageIcon lbl = new ImageIcon("Image/story4.jpg");
            lbl4.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl4.setIcon(lbl);
        }
        if(level >= 5){
            ImageIcon lbl = new ImageIcon("Image/story5.jpg");
            lbl5.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl5.setIcon(lbl);
        }
        if(level >= 6){
            ImageIcon lbl = new ImageIcon("Image/story6.jpg");
            lbl6.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl6.setIcon(lbl);
        }
        if(level >= 7){
            ImageIcon lbl = new ImageIcon("Image/story7.jpg");
            lbl7.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl7.setIcon(lbl);
        }
        if(level >= 8){
            ImageIcon lbl = new ImageIcon("Image/story8.jpg");
            lbl8.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl8.setIcon(lbl);
        }
        if(level >= 9){
            ImageIcon lbl = new ImageIcon("Image/story9.jpg");
            lbl9.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl9.setIcon(lbl);
        }
        if(level >= 10){
            ImageIcon lbl = new ImageIcon("Image/story10.jpg");
            lbl10.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl10.setIcon(lbl);
        }
        if(level >= 11){
            ImageIcon lbl = new ImageIcon("Image/story11.jpg");
            lbl11.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl11.setIcon(lbl);
        }
        if(level >= 12){
            ImageIcon lbl = new ImageIcon("Image/story12.jpg");
            lbl12.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl12.setIcon(lbl);
        }
        if(level >= 13){
            ImageIcon lbl = new ImageIcon("Image/story13.jpg");
            lbl13.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl13.setIcon(lbl);
        }
        if(level >= 14){
            ImageIcon lbl = new ImageIcon("Image/story14.jpg");
            lbl14.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl14.setIcon(lbl);
        }
        if(level >= 15){
            ImageIcon lbl = new ImageIcon("Image/story15.jpg");
            lbl15.setIcon(lbl);
        }else{
            ImageIcon lbl = new ImageIcon("Image/storyLock.jpg");
            lbl15.setIcon(lbl);
        }
        //BACKGROUND ON THE LAST ORDER
        ImageIcon raw1 = new ImageIcon("Image/BackgroundStory.jpg");
        Image img1 = raw1.getImage();
        Image newImg1 = img1.getScaledInstance(800, 600, Image.SCALE_SMOOTH);
        ImageIcon finalImage1 = new ImageIcon(newImg1);
        JLabel lblBackground = new JLabel(finalImage1);
        
        lblBackground.setBounds(0, 0, 800, 600);
        this.add(lblBackground);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lbl9;
    // End of variables declaration//GEN-END:variables
}
