
package harrypotter;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author KELVIN
 */
public class tutorArena extends javax.swing.JPanel {
    
    bot dummy = new bot(0);
    int npcMaxMana = dummy.mana;
    int npcHpMax = dummy.hp;
    int text = 0;
    int resetPlayer = 2;
    int time = 1000;
    Timer myTimer;
    public tutorArena() {
        initComponents();
        this.setSize(800,600);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(102, 51, 0)));
        jPanel1.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 80, 80);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 30, 80, 80);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 30, 80, 80);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(1);
        jTextArea1.setRows(1);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 30, 476, 30);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(1);
        jTextArea2.setRows(1);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(290, 90, 476, 30);

        jLabel4.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NPC");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 70, 360, 19);

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PLAYERNAME");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(290, 10, 360, 19);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("2");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(720, 10, 40, 20);

        add(jPanel1);
        jPanel1.setBounds(10, 460, 780, 130);

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NPC_HP/NPC_HP_MAX");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 10, 310, 20);

        add(jPanel2);
        jPanel2.setBounds(450, 20, 330, 40);

        jPanel3.setBackground(new java.awt.Color(0, 51, 0));
        jPanel3.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PlayerHP/PlayerHPMax");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 10, 310, 20);

        add(jPanel3);
        jPanel3.setBounds(20, 20, 330, 40);

        jLabel8.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 48)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("VS");
        add(jLabel8);
        jLabel8.setBounds(360, 30, 80, 40);
        add(jLabel9);
        jLabel9.setBounds(550, 150, 200, 300);
        add(jLabel10);
        jLabel10.setBounds(50, 150, 200, 300);

        jPanel4.setBackground(new java.awt.Color(0, 0, 153));
        jPanel4.setForeground(new java.awt.Color(0, 0, 102));

        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ManaNow/ManaMax");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel4);
        jPanel4.setBounds(140, 60, 210, 20);

        jPanel5.setBackground(new java.awt.Color(0, 0, 153));
        jPanel5.setForeground(new java.awt.Color(0, 0, 102));

        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ManaNow/ManaMax");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel5);
        jPanel5.setBounds(450, 60, 210, 20);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("PlayerName");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel6);
        jPanel6.setBounds(20, 60, 120, 20);

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("NPC_Name");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(jPanel7);
        jPanel7.setBounds(660, 60, 120, 20);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jTextArea3.setRows(1);
        jTextArea3.setText("Welcome to the battleground!");
        jTextArea3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTextArea3);

        add(jScrollPane3);
        jScrollPane3.setBounds(270, 386, 260, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea3MouseClicked
        
    }//GEN-LAST:event_jTextArea3MouseClicked
    public void keyPressed(){
        if(text == 0){
            text = 1;
            jTextArea3.setText("So you are here with a dummy, dont\n" +
"worry it won't hurt you.");
        }else if(text == 1){
            text = 2;
            jTextArea3.setText("You can't go back to see all the spell, so\n" +
"you have to remember it before hand!");
        }else if(text == 2){
            text = 3;
            jTextArea3.setText("Since you are new, i will give you one\n" +
"easy spell to learn.");
        }else if(text == 3){
            text = 4;
            jTextArea3.setText("Now try INCENDIO, but dont use\n" +
"upper character!");
        }else if(text == 4){
            text = 5;
            jTextArea3.setText("incendio, then press ENTER to swing\n" +
"the wand.");
        }else if(text == 5){
            if(jTextArea1.getText().equals("incendio")){
                text = 6;
                jTextArea3.setText("Well done!");
                dummy.hp = 0;
                jLabel6.setText(dummy.hp+"/"+npcHpMax);
            }else{
                jTextArea3.setText("Wrong!!! Try Again!\nincendio.");
            }
        }else if(text == 6){
            text = 7;
           jTextArea3.setText("One more thing, the spell will be reset\n" +
"if you do nothing for 2 seconds.");
        }else if(text == 7){
            text = 8;
            jTextArea3.setText("Remember, be fast, be smart, i think\n" +
"you are ready now!");
        }else if(text == 8){
            text = 9;
            jTextArea3.setText("Now go back the dorm, you are on your\n" +
"own now, see you!");
        }else if (text == 9){
            mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
            temp.goToMainMenu();
        }
    }
    
    public void insertSpell(char e){
        jTextArea1.append(String.valueOf(e));
    }
    public void rebuild(){
        mainFrame temp = (mainFrame)this.getParent().getParent().getParent().getParent();
        temp.p1.spell.add("incendio");
        temp.kodePanel = "ta";
        temp.p1.usedWand = new wand(-1);
        //PLAYER
        player tempP1 = (player) temp.p1.clone();
        jLabel7.setText(tempP1.hp+"/"+temp.p1.hp);
        jLabel13.setText(tempP1.mana+"/"+temp.p1.mana);
        jLabel11.setText(tempP1.nama);
        
        //BOT
        
        jLabel6.setText(dummy.hp+"/"+npcHpMax);
        jLabel14.setText(dummy.mana+"/"+npcMaxMana);
        jLabel12.setText(dummy.nama);
        
        ImageIcon player = new ImageIcon("Image/playerArena.png");
        jLabel10.setIcon(player);
        ImageIcon dummy = new ImageIcon("Image/NPC_dummy.png");
        jLabel9.setIcon(dummy);
        
        //BACKGROUND ON THE LAST ORDER
        ImageIcon raw1 = new ImageIcon("Image/BackgroundArena.jpeg");
        Image img1 = raw1.getImage();
        Image newImg1 = img1.getScaledInstance(800, 600, Image.SCALE_SMOOTH);
        ImageIcon finalImage1 = new ImageIcon(newImg1);
        JLabel lblBackground = new JLabel(finalImage1);
        
        lblBackground.setBounds(0, 0, 800, 600);
        this.add(lblBackground);
        
        
        //GAME SYSTEM
        myTimer = new Timer(time,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                
                if(resetPlayer > 0){
                    resetPlayer--;
                }else{
                    resetPlayer = 2;
                    jTextArea1.setText("");
                }
                System.out.println(resetPlayer);
                jLabel15.setText(String.valueOf(resetPlayer));
            }
        });
        myTimer.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
